### PR TITLE
Change the <button> to <input type="submit">

### PR DESCRIPTION
**Pull request by ralt**

### CODE REVIEW

**Comment by PeeHaa** [comment]
I would have blindly pulled this PR, but now that asshole @DaveRandom is making me doubt my assumption that using an `input` element is cleaner.

The gist of it is:

> To me, an input is for sending a value, a button is for action-only things (like an "anonymous" for submit)

[source](http://chat.stackoverflow.com/transcript/message/27696758#27696758).

I will try to get some more eyes / opinions on it.

**Comment by morrisonlevi** [comment]
I think buttons are better. I agree that inputs are for sending data and buttons are for actions.

**Comment by Tyler-H** [comment]
I agree that buttons are for actions. Input fields are for sending information, whether it's text, a binary, etc.

**Comment by picodealion** [comment]
I agree with @morrisonlevi  and @Tyler-H

**Comment by MadaraUchiha** [comment]
`<button>`s ftw. Also, more stylable and supports pseudo elements.

**Comment by WesNetmo** [comment]
<input type="submit|button|image"> are from html 3.2 era

**Comment by morrisonlevi** [comment]
I think we are in agreement. We favor `<button>`. Closing...

**Pull request closed without merging**
