### PR TITLE
Static analysis fixes

### PR DESCRIPTION
**Pull request by DaveRandom**
\+ minor refactoring/improvements

### CODE REVIEW

**Comment by PeeHaa** [comment]
Need to deploy it to check whether you didn't fuck something up, but looks good to me. <3

**Comment by DaveRandom** [comment]
\*bump\*

**Comment by PeeHaa** [comment]
Sorry @DaveRandom I suck and I feel bad. Will look at it tonight!

**Comment by PeeHaa** [comment]
I am very very sorry... :P

**Pull request merged**
